Vagrant.configure("2") do |config|

  # VM 1 - Control Plane
  config.vm.define "control-plane" do |cp|
    cp.vm.box = "generic/ubuntu2204"
    cp.vm.hostname = "k0s-control-plane"
    cp.vm.network "private_network", ip: "192.168.56.11", hostname: true

    # File provision
    cp.vm.provision "file", source: "./resolv.conf", destination: "~/resolv.conf"
    cp.vm.provision "shell", path: "./provision.sh"

    cp.vm.provider "virtualbox" do |v|
      v.name = "k0s-control-plane"
      v.memory = 2048
      v.cpus = 2
    end
  end

  # VM 2 - Worker 1
  config.vm.define "worker-1" do |worker_1|
    worker_1.vm.box = "generic/ubuntu2204"
    worker_1.vm.hostname = "k0s-worker-1"
    worker_1.vm.network "private_network", ip: "192.168.56.21", hostname: true

    # File provision
    worker_1.vm.provision "file", source: "./resolv.conf", destination: "~/resolv.conf"
    worker_1.vm.provision "shell", path: "./provision.sh"

    worker_1.vm.provider "virtualbox" do |v|
      v.name = "k0s-worker-1"
      v.memory = 2048
      v.cpus = 2
    end
  end

  # VM 3 - Worker 2
  config.vm.define "worker-2" do |worker_2|
    worker_2.vm.box = "generic/ubuntu2204"
    worker_2.vm.hostname = "k0s-worker-2"
    worker_2.vm.network "private_network", ip: "192.168.56.22", hostname: true

    # File provision
    worker_2.vm.provision "file", source: "./resolv.conf", destination: "~/resolv.conf"
    worker_2.vm.provision "shell", path: "./provision.sh"

    worker_2.vm.provider "virtualbox" do |v|
      v.name = "k0s-worker-2"
      v.memory = 2048
      v.cpus = 2
    end
  end

end