apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: PUBLIC_OR_PRIVATE_IP_ADDRESS
      user: vagrant
      port: 22
      keyPath: VAGRANT_SSH_PUB_KEY
    role: controller+worker
    privateAddress: PUBLIC_OR_PRIVATE_IP_ADDRESS
  - ssh:
      address: PUBLIC_OR_PRIVATE_IP_ADDRESS
      user: vagrant
      port: 22
      keyPath: VAGRANT_SSH_PUB_KEY
    role: worker
    privateAddress: PUBLIC_OR_PRIVATE_IP_ADDRESS
  - ssh:
      address: PUBLIC_OR_PRIVATE_IP_ADDRESS
      user: vagrant
      port: 22
      keyPath: VAGRANT_SSH_PUB_KEY
    role: worker
    privateAddress: PUBLIC_OR_PRIVATE_IP_ADDRESS
  k0s:
    version: 1.27.1+k0s.0
    dynamicConfig: false
