apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.56.11
      user: vagrant
      port: 22
      keyPath: /Users/nurimansyah/Developments/Youtube/repo/belajar-k0s-distribution/vagrant/.vagrant/machines/control-plane/virtualbox/private_key
    role: controller+worker
    privateAddress: 192.168.56.11
  - ssh:
      address: 192.168.56.21
      user: vagrant
      port: 22
      keyPath: /Users/nurimansyah/Developments/Youtube/repo/belajar-k0s-distribution/vagrant/.vagrant/machines/worker-1/virtualbox/private_key
    role: worker
    privateAddress: 192.168.56.21
  - ssh:
      address: 192.168.56.22
      user: vagrant
      port: 22
      keyPath: /Users/nurimansyah/Developments/Youtube/repo/belajar-k0s-distribution/vagrant/.vagrant/machines/worker-2/virtualbox/private_key
    role: worker
    privateAddress: 192.168.56.22
  k0s:
    version: 1.27.1+k0s.0
    dynamicConfig: false
